{{- $fullName := include "qlik-mashup.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "qlik-mashup.name" . }}
    chart: {{ template "qlik-mashup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: {{ printf "http://%s-edge-auth.%s.svc.cluster.local:8080/v1/auth" .Values.ingress.targetAuthReleaseName .Release.Namespace | quote }}
    nginx.ingress.kubernetes.io/auth-signin: https://$host/login?returnto=$request_uri
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ template "qlik-mashup.fullname" . }}
              servicePort: {{ .Values.service.port }}
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
